### PR TITLE
Use the right id for the org_id placeholder

### PR DESCRIPTION
**Pull request by rubenporras**

### CODE REVIEW

**Review by netomi — DISMISSED** [review]

**Review by netomi — COMMENTED** [review]
Actually, this placeholder is replaced when the documentation site is being built:

https://github.com/eclipse-lsp4e/.eclipsefdn/blob/main/mkdocs.yml#L37

**Comment by netomi** [comment]
The site is also built correctly, you can verify here: https://eclipse-lsp4e.github.io/.eclipsefdn/

Will close this PR.

**Comment by rubenporras** [comment]
Thanks, I understand now how the placeholder works.

**Pull request closed without merging**
